
run initialized
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00,  8.60it/s]
Traceback (most recent call last):
  File "/home/ssc255/nlp/ner_experiments/src/bilstm_crf_runner.py", line 197, in <module>
    main(args=args, config=wandb.config, run_id=run.id)
  File "/home/ssc255/nlp/ner_experiments/src/bilstm_crf_runner.py", line 110, in main
    train_dataloader = DataLoader(dataset=train_data, batch_size=config.batch_size, shuffle=True, collate_fn=pad_batch)
AttributeError: 'dict' object has no attribute 'batch_size'